#ifndef __QSEE_SYSCALLS_H__
#define __QSEE_SYSCALLS_H__

#define QSEE_CIPHER_INIT (0xFFFFFFE9)

#define QSEE_GET_SW_FUSE (0xFFFFFFF7)

#define QSEE_PRNG_SYSCALL (0xFFFFFFE2)

#define QSEE_SYSCALL_8 (0xFFFFFFF8)

#define QSEE_REGISTER_SHARED_BUF (0xFFFFFF04)

#define QSEE_DEREGISTER_SHARED_BUF (0xFFFFFFFC)

#define QSEE_PREPARE_SECURE_READ (0xFFFFFF07)

#define QSEE_UNPREPARE_SECURE_READ (0xFFFFFF05)


#endif
